## Install numpy library

```
pip install numpy
```

### Import numpy 

In [1]:
# as np ti create a alias on numpy lib.
import numpy as np

### Create vector

In [5]:
import numpy as np

# Create a row vector
row_vector = np.array([10,15,20])
print("Vector\n ", row_vector)

# Create a column vector
column_vector = np.array([[10], [20], [30]])
print(" Column\n",column_vector)

Vector
  [10 15 20]
 Column
 [[10]
 [20]
 [30]]


### Create matrix 

In [3]:
import numpy as np

# Create a matrix
matrix = np.array([[10, 20, 30], [10, 20, 30], [10, 20, 30]])
print(matrix)

[[10 20 30]
 [10 20 30]
 [10 20 30]]


### Accessing Elements

In [13]:
import numpy as np

# Create a vector as a row
row_vector = np.array([10, 20, 30, 40, 50, 60, 70, 80,90])
print("vector \n", row_vector)

# Create a Matrix
matrix = np.array([[10, 20, 30], [40, 50, 60], [70, 80,90]])
print("matrix \n", matrix)

# Select 2nd element of vector
print("row_vector[1] \n", row_vector[1])

# Select 3rd row 3rd column
print("matrix[2,2] \n", matrix[2,2])

# Select all elements of a vector
print("row_vector[:] \n", row_vector[:])

# Select the last element
print("row_vector[-1] \n", row_vector[-1])

# Select the first 2 rows and all columns of the matrix
print("matrix[:2,:] \n", matrix[:2,:])



vector 
 [10 20 30 40 50 60 70 80 90]
matrix 
 [[10 20 30]
 [40 50 60]
 [70 80 90]]
row_vector[1] 
 20
matrix[2,2] 
 90
row_vector[:] 
 [10 20 30 40 50 60 70 80 90]
row_vector[-1] 
 90
matrix[:2,:] 
 [[10 20 30]
 [40 50 60]]


### Matrix

In [15]:
import numpy as np

# Create matrix
matrix = np.array([[10, 20, 30], [40, 50, 60], [70, 80,90]])

# View the number of rows and columns
print("Rows and Columns \n", matrix.shape)

# View the number of elements (rows*columns)
print("Total elements \n", matrix.size)

# View the number of dimensions 
print("Dimensions \n", matrix.ndim)


Rows and Columns 
 (3, 3)
Total elements 
 9
Dimensions 
 2


### Min and Max

In [16]:
import numpy as np

# Create matrix
matrix = np.array([[10, 20, 30], [40, 50, 60], [70, 80,90]])

# Return the max element
print(np.max(matrix))

# Return the min element
print(np.min(matrix))

# To find the max element in each column
print(np.max(matrix, axis=0))

# To find the max element in each row
print(np.max(matrix, axis=1))


90
10
[70 80 90]
[30 60 90]


### Calculate average

In [17]:
import numpy as np

# Create matrix
matrix = np.array([[10, 20, 30], [40, 50, 60], [70, 80,90]])

# Mean 
print(np.mean(matrix))

50.0


### Reshape

In [18]:
import numpy as np

# Create matrix
matrix = np.array([[10, 20, 30], [40, 50, 60], [70, 80,90]])

# Reshape
print(matrix.reshape(9,1))

# Here -1 says as many columns as needed and 1 row
print(matrix.reshape(1,-1))

# If we provide only 1 value Reshape would return a 1-d array of that length
print(matrix.reshape(9))

# We can also use the Flatten method to convert a matrix to 1-d array
print(matrix.flatten())


[[10]
 [20]
 [30]
 [40]
 [50]
 [60]
 [70]
 [80]
 [90]]
[[10 20 30 40 50 60 70 80 90]]
[10 20 30 40 50 60 70 80 90]
[10 20 30 40 50 60 70 80 90]


### Transpose

In [19]:
import numpy as np

# Create matrix
matrix = np.array([[10, 20, 30], [40, 50, 60], [70, 80,90]])

# Transpose the matrix
print(matrix.T)

[[10 40 70]
 [20 50 80]
 [30 60 90]]


### Diagonal

In [20]:
import numpy as np

# Create matrix
matrix = np.array([[10, 20, 30], [40, 50, 60], [70, 80,90]])

# Print the principal diagonal
print(matrix.diagonal())

[10 50 90]


### Dot Product

In [22]:
import numpy as np

# Create vector 1
vector_1 = np.array([10, 20, 30])

# Create vector 2
vector_2 = np.array([[40], [50], [60]])

# Calculate dot product
print(np.dot(vector_1, vector_2))

[3200]


### Adding, Subtracting and Multiplying Matrices

In [1]:
import numpy as np

# Create matrices
matrix_1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8,9]])

matrix_2 = np.array([[7, 8,9],[4, 5, 6],[1, 2, 3]])

# Add the two matrices
print(np.add(matrix_1, matrix_2))

# Subtraction
print(np.subtract(matrix_1, matrix_2))

# Multiplication (Element wise)
print(matrix_1 * matrix_2)

# Multiplication (row column wise)
print(matrix_1 * matrix_2)

[[ 8 10 12]
 [ 8 10 12]
 [ 8 10 12]]
[[-6 -6 -6]
 [ 0  0  0]
 [ 6  6  6]]
[[ 7 16 27]
 [16 25 36]
 [ 7 16 27]]
[[ 7 16 27]
 [16 25 36]
 [ 7 16 27]]


### Zeros and ones

In [3]:
import numpy as np

# Zeros
zeros = np.zeros([4,4])
print(zeros)

# Ones
ones = np.ones([3,3])
print(ones)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


### Generate random values

In [4]:
import numpy as np

# Generate 3 random integers b/w 1 and 10
print(np.random.randint(0,11,3))

# Draw 3 number from a normal distribution with mean 1.0 and std 2.0
print(np.random.normal(1.0, 2.0, 6))

[9 6 3]
[ 4.88641983 -0.92751525  4.72133708 -3.29843636  3.9936074   0.84869199]


### Solve linear sistem

In [1]:
import numpy as np

# Matrix
matrix = np.array([[2,4,6],[4,5,6],[3,1,-2]])

vector = np.array([18,24,4])

# Solve
print( np.linalg.solve(matrix, vector) )


[ 4. -2.  3.]
